import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/page";
import SideBar from "@/components/SideBar/page";
import Banner from "@/components/Banner/page";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} bg-[#EAEAEA]`} suppressHydrationWarning={true}>
        <Navbar />
        <div className="flex">
          <SideBar />
          <div className="flex flex-col">
            <Banner title="Home" />
            <div className="bg-white mt-10 ml-10 shadow-semua-sisi p-8">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
